failed build check

diff --git a/buildme b/buildme
--- a/buildme
+++ b/buildme
@@ -9,6 +9,10 @@ tree > build/index.html
 #build packages and more to output
 echo "[Info] building packages"
 ./source/build-all
+if [ "$?" != "0" ];then
+    echo "[error] building packages failed" 
+    exit 1
+fi
 
 echo "[Info] building repo"
 ./repo/builder
diff --git a/source/build-all b/source/build-all
--- a/source/build-all
+++ b/source/build-all
@@ -11,6 +11,10 @@ for buildme in ./packages/*/buildme; do
     echo "[Info] running ${buildme}"
     chmod +x "./${buildme}"
     "./${buildme}" "$(pwd)/../output"
+    if [ "$?" != "0" ];then
+        echo "[error] failed to build ${buildme}" 
+        exit 1
+    fi
 
 done
 
